### PR TITLE
Support domain

### PR DESCRIPTION
**Pull request by ocalvo**
I am running with an local active directory and domain is required.

### CODE REVIEW

**Review by marcone — COMMENTED** [review]
Seems like you forgot to add some files? (as written, this only adds a variable to a file, which then never gets used)
Also, please squash all commits together and upload a single change (i.e. use `git rebase -i` and `git push --force`)

**Comment by ocalvo** [comment]
It works for me, do you know where to add the new variable?

**Review by marcone — COMMENTED** [review]
This still won't work, because all this does is add a "sharedomain" variable in the setup config, but that variable isn't used by anything. You would have to add code to update the cifs credentials file.

**Comment by ocalvo** [comment]
Maybe I am missing something but this change does include a file change that will update the tmp credentials file.

**Comment by marcone** [comment]
Oh, sorry, I was just looking at the last change.
Can you please squash all changes together, as [mentioned here](https://github.com/marcone/teslausb#contributing)?

**Comment by marcone** [comment]
Also, even when considering all the changes together, I suspect this will fail with an "unbound variable" error when `sharedomain` is not set.

**Comment by Gawdl3y** [comment]
Just a heads up, GitHub allows collaborators to automatically squash all commits into one upon merging a PR - on the merge button, click the arrow, and select "Squash and merge". No need to request contributors making a PR to squash their commits manually anymore.

**Comment by marcone** [comment]
Yes, I know I can squash all the commits when merging. I want them squashed *before* merging, so I can review the entire change as a whole.

**Comment by ocalvo** [comment]
The "changes" tab display the change as a whole. Why this does not work for you?

**Comment by marcone** [comment]
I never realized I could see all changes at once under "Files changed". I'd just been clicking on the individual commits listed here in the "conversation" view, in which case it only shows  changes for that commit.
Thanks for pointing that out to me.

**Comment by marcone** [comment]
FYI: this PR still needs fixing to handle the case where the domain is not specified, which with the current PR will result in a "sharedomain: unbound variable" error.

**Pull request closed without merging**
