### PR TITLE
Improved boombox

### PR DESCRIPTION
**Pull request by robotros**

### CODE REVIEW

**Comment by marcone** [comment]
A few problems I see with this change:
- it's not actually necessary. People that aren't using music sync can just create the folder themselves when they want to add custom boombox files
- people that *are* using music sync and want to use custom boombox files should create the boombox folder and files on their music share
- for people that are using music sync but aren't adding boombox files, the directory will be created every time the music drive is mounted on the Pi, and then deleted again by music sync.

**Comment by robotros** [comment]
I understand what you are saying. There has been a lot of confusion on how  exactly boombox works and what was needed.
That being said. The code creates the boombox folder both on the Music portion of the drive and the on the Music Archive for those that are using music sync.

That way the folders are there by default for those that plan to use them.  Its not at all necessary but would be a nice feature that makes the setup a little easier and people can see the folder right away and how to use it.

For people that are using sync but not adding boombox files it should just create an empty folder on both the share and the music drive. if the user isn't deleting the folder it wouldn't delete and recreate it on its own.

**Comment by marcone** [comment]
> That being said. The code creates the boombox folder both on the Music portion of the drive and the on the Music Archive for those that are using music sync.

Ah sorry, I misread your change.  I don't really like that the Pi creates a folder in the archive, and also as written, it'll cause the entire archive and sync operation to fail if the music archive is not writable.

How about not creating it on the archive, but only on the disk image when it is first created?

**Comment by marcone** [comment]
Closing for the reasons mentioned in my earlier comment.

**Pull request closed without merging**
