### PR TITLE
New option DISABLE_SENTRY to always disable sentry mode

### PR DESCRIPTION
**Pull request by RichieB2B**
Somehow TeslaUSB forgets to disable sentry mode when it is done. This causes a lot of SoC loss for me. This option makes it possible to force TeslaUSB to always disable sentry mode when the file uploads are done.

### CODE REVIEW

**Comment by marcone** [comment]
teslausb can't "forget" to turn sentry back off. The logic in the code is such that it will always attempt to turn sentry mode back off if it previously turned it on. However, there is no check that it actually successfully turned sentry off. It does log the result in the log file, so if it failed to turn it off, you should see this in /mutable/archiveloop.log
In fact, since teslausb logs all the interactions with the Tesla API to archiveloop.log, you should probably have a look there to see whether it though sentry mode was on or off when it started, and whether it attempted/succeeded in turning it back off afterward. 

In any case, if the only way for Sentry to remain on is for the "turn off" API call to fail, having a separate mechanism to do the same thing is not really going to help. It's going to make the same API call, and it'll be just as likely to fail.
A better solution might be to check that sentry mode is actually off after the attempt to turn it off is done, and keep trying to turn it off.

**Comment by RichieB2B** [comment]
I agree with you that the current code and logic is not flawed. It it was I would try to fix it. :-)
What I see happening is: TeslaUSB turns sentry mode on, and starts uploading files. Because of poor wifi this takes a long time. Before TeslaUSB is done, the USB power is cut (I'm not sure why). At some point (during charging at night) TeslaUSB becomes active again. It notices sentry mode is already on and never turns it off.

**Comment by marcone** [comment]
Hmm, it shouldn't cut power to the USB ports while Sentry mode is on. I mean that's the whole point of this feature: to keep the Pi powered on by turning on Sentry.
That being said, there was another report (https://github.com/marcone/teslausb/issues/384) about power to the ports being turned off while Sentry mode is on, so maybe the car is trying to be smart and is aggressively turning them off anyway when it doesn't see a USB drive.

So in that case a better solution might be to go back to something like what teslausb did initially: use the Tesla API to wake the car up every minute for the duration of the archive.
This is slightly more complicated to implement, because it needs to be done in a background process, but the advantage would be that once the Pi stops sending the request (because it somehow turned off anyway, or because it crashed, or whatever other reason), the car will turn off automatically after a few minutes.

**Comment by RichieB2B** [comment]
That should work as well. What I like about the Sentry Mode solution is that I can manually override it using the Tesla app. If TeslaUSB takes too long (car is parked just barely inside the wifi range and uploading files takes literaly forever) I can easily decide to shut it down.

**Comment by simonrb2000** [comment]
I have found Sentry off to be flaky with TeslaUSB. I think it's better if TeslaUSB turns on Sentry mode. My scenario is that we get home, kids get out and car connects to the network and starts uploading files, I then have to get in the car and put it in the garage. Sentry mode turns off so I have to turn it back on to ensure that it doesn't cut power to the USB's while uploading. This works however then it won't turn off Sentry mode so I keep an eye on the uploads and turn Sentry mode off from the app. I need to dig into settings and change the delay to 5mins or something like that. 

I also like your idea Marcone to keep the car awake every minute. As long as that keeps USB's powered up :)

**Comment by bookernath** [comment]
I think perhaps something has changed with Sentry Mode in recent tesla software updates, there may even be a bug...

e.g. https://www.reddit.com/r/TeslaModel3/comments/g8gkhr/anyone_notice_your_car_can_sleep_while_sentry/

**Comment by marcone** [comment]
I won't be merging this, because it will just replace one unintentional behavior with another (it will turn Sentry off always, even if you had manually turned it on previously).
I'm working on making archiving work without disconnected the drive from the car, which may help with USB powering down.

**Comment by RichieB2B** [comment]
Excellent, thanks!

**Pull request closed without merging**
