### PR TITLE
rsync via mounted CIFS dir

### PR DESCRIPTION
**Pull request by sboesebeck**
Hi,

I took the cifs-scripts as a basis and just changed the file copy part. It uses `rsync` now to copy files. In theory this should speed up things a bit. 
Directories will be deleted when rsync finished.
the archive-system is called `cifsrsync`, the rest of the settings remains same compared to `cifs`.

it worked here in a test environment, have to test it in the wild though.

### CODE REVIEW

**Comment by sboesebeck** [comment]
one other thing - for testing I added a "feature": if you create a file in /tmp/ called `not_reachable` the system will simulate a non reachable archive. This way you can force a sync:

`touch /tmp/not_reachable ; tail -f /mutable/archiveloop.log`

look at the log... takes about 10s depending on your config

`rm /tmp/not_reachable; tail -f /mutable/archiveloop.log`

now you can see the system starting...

Not sure if there is some other way of testing things, just wanted to mention it...

And: there is also the option to create a file callled `reachable`- this would cause the system to think, the archive is reachable, even if it may not - caution, this might lead to data loss... just for testing purpose

**Comment by marcone** [comment]
> one other thing - for testing I added a "feature": if you create a file in /tmp/ called `not_reachable` the system will simulate a non reachable archive. This way you can force a sync:
> 
> `touch /tmp/not_reachable ; tail -f /mutable/archiveloop.log`
> 
> look at the log... takes about 10s depending on your config
> 
> `rm /tmp/not_reachable; tail -f /mutable/archiveloop.log`
> 
> now you can see the system starting...
> 
> Not sure if there is some other way of testing things, just wanted to mention it...

There is already a way to do this: look for `archive_is_unreachable` in archiveloop.

> And: there is also the option to create a file callled `reachable`- this would cause the system to think, the archive is reachable, even if it may not - caution, this might lead to data loss... just for testing purpose

Similarly, there is already a way to do this: look for `archive_is_reachable` in archiveloop.

**Comment by marcone** [comment]
This is superseded by https://github.com/marcone/teslausb/pull/319, right?

**Comment by marcone** [comment]
No longer needed.

**Pull request closed without merging**
