### PR TITLE
Add support for cm4

### PR DESCRIPTION
**Pull request by t-jonesy**
Adds CM4 to the devices that will pass the verify check

### CODE REVIEW

**Comment by marcone** [comment]
I've just removed the hardware check, so this is no longer necessary.
Out of curiosity, what carrier board are you using with the CM4 to run teslausb?

**Comment by t-jonesy** [comment]
This is the one I'm using for now, I've got to see if I can modify it to not boot in emmc flashing mode when the switch is set to use the usb-c port. It's working as long as I boot the pi with the switch set to off and then move it to on. Not ideal, but it's working and the CM4 was all I could find at retail prices.

https://www.pishop.us/product/nano-base-board-a-for-raspberry-pi-compute-module-4/

**Comment by t-jonesy** [comment]
no longer needed after hw check removal

**Comment by t-jonesy** [comment]
@marcone since the hardware check was added back in 5903164 would you mind merging this?

**Comment by t-jonesy** [comment]
also, if you're curious, I ended up getting the splitter cable linked in the readme and a usb A to usb A cable and that setup has been working well.

**Pull request closed without merging**
