### PR TITLE
RFC: Change the way snapshots are used.

### PR DESCRIPTION
**Pull request by allanbank**
First - This is not really a pull request. It is a request-for-comments. 

I have been playing with a few different ideas to try and solve the "drive too slow" and also implement the ability to move the recent clips off of the RPi and onto the archive server.

General concept as implemented here:
1. The background snapshot loop now copies the files out of the snapshot into /backingfiles/TeslaCam instead of mounting the snapshot permanently and using a series of soft links. (I have a theory that a large number of shared blocks is part of the cause of the "slow usb drive". No proof other than it seems to help.)
2. All of the archiveclips.sh have a consistent command line interface that supports copy and move semantics. This is tested for CIFS. 
3. All of the I/O operations us a ionice to ensure they are behind the _file-storage_ thread for the car.
4. The main archive thread moves files from the cam-drive-image to the /backingfiles/TeslaCam directory and then moves them to the archive.
    * This is to reduce the time that the car does not see the drives mounted.
4. The snapshot loop can now copy files to the archive (this avoids re-copying a file to the archive on each snapshot). 
5. Update the priority of the file-storage thread to the highest priority using ionice.
6. Have the snapshotloop detect when the car stops writing files.
    * This needs some work as it does not detect when the car stops but recent clips are getting moved away.
7. There is a new option to copy the recent clips.
    * This can take a long time.
    * I think we will also needs to disable the car creating more clips if this has any hope if keeping up.
8. The snapshotloop now waits for after a spike/surge in I/O to the drive (presumably from the _file-storage_ thread) before taking a snapshot.

Things I know need work:
* The snapshot for the music image is not working because the snapshot is mounted read-only. Its an easy fix but low on the list.
* I think the amount of code in archiveloop file is getting out of hand. I separated the two modes into a different set of functions but the code needs more organization (IMO). At this point I am planning to move the functions into "sourceable" files but I am open to other suggestions.
* The rsync and rclone archiveclips scripts needs to be tested.

I have been using a version of this code on my Pi0 and it works. I would appreciate additional testers but please realize it is all a work in progress.

If the general strategy looks reasonable I will try and create a new series of patches that are more easily digested. Again, comments are welcomed.

### CODE REVIEW

**Comment by marcone** [comment]
Some initial thoughts:
I don't really like the idea of copying the files. It effectively doubles every write and thus doubles the wear on the card. I'd have to see some compelling evidence that the presence of snapshots slows down writes.
I do like the idea of waiting until after a write from the car to take a snapshot. I've been wanting to do that myself, just haven't gotten around to it yet.
I see that you changed the snapshot interval to every 15 minutes, however the car records  about 1.8GB of data in 15 minutes, and I don't think it's possible to copy all that data before the car does the next write, so it will be copying files while the car is trying to write at the same time. I guess that's where using 'ionice' comes in?

**Comment by allanbank** [comment]
> I don't really like the idea of copying the files. It effectively doubles every write and thus doubles the wear on the card. I'd have to see some compelling evidence that the presence of snapshots slows down writes.

Agreed. It did help shorten length amount of time to complete the snapshot copy. That was on the order of 10+ seconds before but is now on the order of a few seconds. 

I think we need to add some form of system monitoring to the mix so we can figure out the root cause of the slow usb. I have been running under the assumption that it is I/O but it could be CPU or memory too. I was looking/thinking about adding systat to collect data over time but I need to figure out how to control the location of the data files.

Are you opposed to me adding options to switch between links and copies so we can collect some performance data for both? Switching would not be "advertised" in the setup templates.

> I see that you changed the snapshot interval to every 15 minutes, however the car records about 1.8GB of data in 15 minutes, and I don't think it's possible to copy all that data before the car does the next write, so it will be copying files while the car is trying to write at the same time. I guess that's where using 'ionice' comes in?

Yes, the ionice keeps the copies out of the way of the file-storage. The file-storage is in the default best-effort class at highest priority and the copies are in the idle class. The ionice does something because I have had several copies of files to remote systems at the same time and I can see the volume of data into the target devices drop periodically.

**Comment by marcone** [comment]
> Yes, the ionice keeps the copies out of the way of the file-storage. The file-storage is in the default best-effort class at highest priority and the copies are in the idle class. The ionice does something because I have had several copies of files to remote systems at the same time and I can see the volume of data into the target devices drop periodically.

Interesting, because I ran some tests with ionice and concluded it has no noticeable effect.
I connected a Pi0 to a linux laptop, mounted the CAM drive on the laptop, and then ran `dd if=/dev/zero of=/media/marcone/CAM/zeroes.dat bs=1M oflag=direct` on the laptop to start moving data to the Pi. While that was running, I also ran `iotop -qqq -p $(pgrep -x dd)` on the laptop to track throughput of the `dd` process over time, and could see it copying a fairly steady 18 MB/sec or so.
Then on the Pi, I ran `dd if=/dev/zero of=/backingfiles/zeroes.dat bs=1M` which immediately resulted in a drastic reduction of throughput as seen by `iotop` on the laptop, with it sometimes even dropping down to zero for a few seconds.
I then ran `ionice -c 1 -n 0 -p $(pgrep -x file-storage)` on the Pi to set the file-storage process to the "realtime" I/O scheduling class with highest priority and restarted the measurement, but it did not make a difference: there was still a dramatic drop in throughput as seen by the laptop, and it sometimes still dropped down to zero for a few seconds.
Even running the `dd` on the Pi as `ionice -c 3 dd ...` to run it at the "idle" priority did not make a difference. I thought that was especially surprising since the man page for `ionice` specifically says that "The impact of an idle I/O process on normal system activity should be zero"
Thinking that perhaps CPU starvation was an issue, I also tried using `renice` to bump the priority of the file-storage process, but it had no effect either.

Now, all of this may be entirely meaningless, since we don't know how the car actually writes to the drive, or how it decides that the drive is too slow, but it might be interesting to see if you can confirm/refute these results.

**Comment by marcone** [comment]
Doing some brief research (i.e. a Google search for "ionice doesn't work" and clicking on the first promising result), I found [this discussion](https://serverfault.com/questions/353881/ionice-without-effect) which claims that ionice doesn't work with all I/O schedulers.
On my Pi0, the available schedulers are:
```
~# cat /sys/block/mmcblk0/queue/scheduler 
[mq-deadline] kyber none
```
but looking at [this page](https://wiki.ubuntu.com/Kernel/Reference/IOSchedulers) which has an overview of the various schedulers, the only references I can find to priorities are for "kyber" and "cfq", with the latter specifically saying that "Priorities from ionice are taken into account", while "kyber" only says that it "should provide quick completion time for requests that are high priority".
I'll have to try this "kyber" scheduler and see if it makes any difference.

**Comment by marcone** [comment]
I ran some tests with ionice and the "kyber" I/O scheduler but the results were very inconsistent.
At first it seemed that kyber allowed me to get better results under load when `ionice`ing the file-storage process, however when I repeated the test after a reboot, the default "mq-deadline" scheduler performed much better, and didn't seem to slow down the file-storage process at all when I ran `dd` on the Pi itself, while "kyber" caused significant slowdown in the file-storage process when faced with concurrent writes on the Pi, and that slowdown seemed to persist for a while even after stopping the writes on the Pi.
When I ran the test again later, it showed "mq-deadline" clearly slowing down the file-storage process again, though not nearly as bad as during the initial tests.
So not sure what to think about that. It does appear that `ionice` has no effect when using the default "mq-deadline" I/O scheduler.

**Comment by fredvanwest-zz** [comment]
I had wondered if having a more performant SD card would make a difference but this discussion seems to defy that intuition. I was pretty happy with teslausb prior to the V9 upgrade but maybe performance was just on the edge and with the addition of the rear camera it was enough to push it over? Has anyone tried a better SD card? If not, would external storage help? I'm finding my USB stick won't even keep up any more.

**Comment by allanbank** [comment]
Sorry - I was out of town.

I have been running some sysbench runs with the various schedulers and can confirm that it looks like the ionice has no impact (actually might make the -c 2 case worse than -c 3). Test results are [here](https://docs.google.com/spreadsheets/d/1vKKzYKD28QkQhqivi6vZqWZehQEeOYyQr4lfog7XDIU/edit?usp=sharing):

I am seeing some very weird I/O performance fluctuations (without the car doing any writing). The write case for none and mq-deadline were horrible but on re-running were inline with kyber.

I am trying to make the test runs more consistent.

**Comment by allanbank** [comment]
I got the sysbench command running in a loop with the random read/write workload.

There is no compelling difference between the kyber and mq-deadline schedulers. 'none' is horrible for the maximum operation time.

I also discovered that about every 10 to 11 minutes sysbench would report a max time for an operation of 3,000+ ms (>3s). All of the data and command are in the [google sheets document](https://docs.google.com/spreadsheets/d/1vKKzYKD28QkQhqivi6vZqWZehQEeOYyQr4lfog7XDIU/edit?usp=sharing) (look at the Cache Tests tab). 

I thought maybe the issue was with the caches and there being some background task flushing and that causing the issue. I added a 'sync' command between runs. Long operation is still there.

I got more aggressive and dropped the file cache. Long operation is still there.

More aggressive and dropped the dentry cache. Long operation is still there.

Maybe if I stop the sysbench from doing any fsyncs? Long operation is still there.

I took a step back and tried to figure out if the issue was with reads, writes, or is it the combination.
* reads: no long operations.
* writes: There a a number of runs that have short maximum operation times and some with longer but not on the order of 3 seconds.

While running the tests I was looking at the system log and noticed and error with:

> Dec 09 03:03:31 teslausb kernel: INFO: task kworker/0:2:12868 blocked for more than 120 seconds.
> Dec 09 03:03:31 teslausb kernel:       Tainted: G         C        4.19.66+ #1253
> Dec 09 03:03:31 teslausb kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
> Dec 09 03:03:31 teslausb kernel: kworker/0:2     D    0 12868      2 0x00000000
> Dec 09 03:03:31 teslausb kernel: Workqueue: events_freezable mmc_rescan

Looking online you can turn that off with a setting in cmdline.txt so I did that and rebooted.

Things got worse. Significantly.

On a hunch I did a: 
    fstrim /backingfiles

After a few minutes the test has calmed down and the maximum operation time (when I am not doing things behind the scenes) has stayed below 200ms and is trending lower.

Can someone try and replicate the results (you will have to manually install the sysbench package and prepare the files for the fileio test).

**Comment by marcone** [comment]
I've added some code that checks when the car is writing, and takes the snapshots inbetween the times when the car is writing.
I took a slightly different approach from yours: instead of looking at writes on the relevant storage device, I look specifically at writes performed by the "file-storage" process (my thinking being that I want to avoid taking a snapshot while the car is writing, but don't really care if something else is writing)

**Comment by allanbank** [comment]
> I took a slightly different approach from yours: instead of looking at writes on the relevant storage device, I look specifically at writes performed by the "file-storage" process (my thinking being that I want to avoid taking a snapshot while the car is writing, but don't really care if something else is writing)

I actually think we do care about all of the I/O. The car may be reading music at the same time and it looks like the car has a pretty good read-ahead because I can see that reflected as spikes in the IO graph. I think the code still refers to the value it is reading as bytes/blocks but it is actually the number of milliseconds that requests are waiting in the queue. What I'm really waiting for is a period congestion and then for the congestion to clear completely. It is write side congestion but it seems to work.

As for the status and plans: I made some fstrim updates to this branch and that has completely stopped the "to slow" errors for me. I have not seen a single error for a week. I still get some 1-2 second pauses when playing music (flac files so a bit of a worst case). My plan is to start cleaning up some of these deltas and submit as a distinct patches for review.

**Comment by marcone** [comment]
I looked into music playback a little too a few weeks ago. It seemed to me that the car has a fixed-size buffer that it reads into, because it reads more frequently for higher-bitrate songs than it does for lower bitrate songs. If I remember correctly it read about every 8 seconds for a 128kbit mp3, so I'm guessing it uses a 128KB buffer.

**Comment by WadeHoltAtNabancard** [comment]
question/observation/thoughts

**Comment by HWadeHolt** [comment]
questions/thoughts; First, I just bought an S and I am playing catchup on this and everything Tesla, including the TeslaCam; My first thought we be if possible, can we just let the Tesla write to an isolated microSD attached to one of the ports, and then use the pi0 to read from it? Perhaps there is no access, hense why it writes to the SD on the pi0, and then offloaded, but with that said, could I then just offload the snapshots or old files written to the onboard sd to an external ssd for later uploading and maintanence; I have a SanDisk Extreme 500G currently plugged into the USB port on the tesla until I get this pi0 loaded and working; My intital thoughts so far from reading all the possible faults and points of failures with using the pi0 with the following:  Get the pi0 as is running, then change then snapshots to move/clean up the primary microsSD files to the external SSD, do any file consiolidation etc using the SSD; use the SSD as a backup and filesystem to upload to network share (and possibly even view from local network???) Thought here is is the reading / writing to the external is slow than so be it; the reading will be fast from the internal sd, writting will be limited to the Tesla writes (for the most part); The external SSD buys me a backup as well as a lot more storage should upload not occur, constant offloading of the onboard sd for ???;

**Comment by allanbank** [comment]
Closing as OBE.

**Pull request closed without merging**
