### PR TITLE
Added timeouts to CIFS and rsync archiving

### PR DESCRIPTION
**Pull request by kdvlr**
This should address the case where the wifi is lost during archive.

### CODE REVIEW

**Review by kdvlr — COMMENTED** [review]
Changed error message

**Comment by marcone** [comment]
I have some reservations about the large timeout for CIFS copying. I can't think of an alternative though. I had hoped to use rsync instead of cp for CIFS and use its timeout, but unfortunately it appears the timeout doesn't work when rsync is just copying between folders.

**Comment by kdvlr** [comment]
Totally Agree! Since the cifs script uses mv, it has to be a wrapper that has to include the time mv actually runs to move the file and then a timeout on top of that. From the archiveloop logs I have seen across multiple issues here, it looks like it takes between 60-75 seconds for most files to be copied. I have seen cases where files have taken more than 160 seconds to copy successfully. I chose 90s because it gives 15-30s as additional buffer. I am sure there will be a few issues raised where some files are not copied because they would have been timed out. 

What's your priority for this repo? Do you prefer availability of dashcam or more reliable copying of files? My preference is more availability of dashcam, so I think that this fix is leaning towards that. There is a higher likelihood that the drive will be attached back without manual intervention with this fix. Worst case files don't get copied, but are still available for a manual retrieval by attaching the pi zero to a PC. 

Rsync works better because it does look for IO. So if within 30s there is no IO, it means that rsync should fail. I am not sure why it does not work for local copies.

**Comment by kdvlr** [comment]
I have been doing some tests for the past weekend and it has been fine. Today again the file copying was stuck moving a  file and it never remounted. Looks like the timeout solution might not be as  good.

**Comment by kdvlr** [comment]
I did confirm that Rsync does not work for local copies. It relies on the network traffic to verify IO, so by design, it will not work for copy between mounts. 

I don't know if there is a better option than the timeout wrapper for CIFS. I'll let you decide if you want to merge this knowing it is not perfect, but mostly works.

**Comment by marcone** [comment]
> I have been doing some tests for the past weekend and it has been fine. Today again the file copying was stuck moving a file and it never remounted. Looks like the timeout solution might not be as good.

Was that with CIFS/mv or with rsync?

**Comment by kdvlr** [comment]
This was with mv. Rsync seems to work reliably.

**Comment by marcone** [comment]
I've been unable to reproduce this problem so far. For me, the mv just exits with a "host is down" message when the connection to the server is lost.

**Comment by marcone** [comment]
@kdvlr I've merged the "Added timeout to rsync" part of your PR, but left out the CIFS part for now, as well as the unrelated push message stuff.
The push message changes should really be a separate PR, and I'm still considering what's the best way to handle the CIFS hangs (which I've been unable to reproduce myself so far)

**Comment by kdvlr** [comment]
Makes sense on the push changes. I'll do a separate PR. 

The CIFS hang doesn't seem to happen very often. I have seen that happen twice over the past 7 days, but I have not been able to find a reliable way to replicate.

**Comment by kdvlr** [comment]
Closing this because separating the changes.

**Pull request closed without merging**
