### PR TITLE
Added Telegram Support for Notifications

### PR DESCRIPTION
**Pull request by kdvlr**
Added Telegram Support for Notifications

### CODE REVIEW

**Comment by kdvlr** [comment]
Not sure why the check fails. I do source the variables, not sure if the shell check is catching those.

**Comment by marcone** [comment]
You can see the failures here: https://github.com/marcone/teslausb/pull/523/checks?check_run_id=1027311487
(expand the "Run ShellCheck" item)

You can get around the `... is referenced but not assigned` by either explicitly disabling that warning, or by making those variables upper case (which makes shellcheck treat them like globals that are set elsewhere)

**Comment by kdvlr** [comment]
@marcone - Is that required to merge this PR ? I just used the existing syntax of lower case (but I now see why WEBHOOK was set to ALL CAPS ).

**Comment by marcone** [comment]
Your choice whether you disable the warning for shellcheck, or convert to uppercase (I prefer the latter since that's the direction I'm going with other code), but fixing the shellcheck failures one way or another is a requirement.

**Comment by kdvlr** [comment]
Sounds good, I will make the changes to upper case.

**Comment by marcone** [comment]
BTW you can run shellcheck locally before uploading the PR by running the `check.sh` script that's part of the teslausb sources. I have it set as a commit hook.
You'll also need to install shellcheck itself, of course.

**Pull request closed without merging**
