### PR TITLE
archiveloop: reduce snapshotloop sleep to 8 minutes

### PR DESCRIPTION
**Pull request by pkuehnel**

### CODE REVIEW

**Review by marcone — COMMENTED** [review]
This should be configurable, with the default being 58 minutes like it is now. The commit message should briefly describe why one might want/need to set it to 8 minutes.

**Comment by pkuehnel** [comment]
Why should it be configureable and why should the default be 58 minutes? If it is 8 minutes it works for everyone (just produces more snapshots) if it is 58 minutes all German (probably European) users can not archive recentClips out of the box. Don't quite understand the disadvantage with 8 minute snapshots.

**Comment by marcone** [comment]
> Don't quite understand the disadvantage with 8 minute snapshots.

There's overhead associated with snapshots, and reducing the snapshot interval like this increases that overhead by a factor of 6-7. That's not something I want to do unless it is necessary, which for many people it isn't. Also, you yourself reported encountering I/O errors after reducing the snapshot interval. That may very well turn out to be unrelated, but it's another reason to not impose this change on everyone just yet.

**Comment by pkuehnel** [comment]
Ok, did not know about the overhead. But as I don't know much about the architecture of your system/how I make this configurable I will update the value manually after each flash/update.

**Comment by pkuehnel** [comment]
BTW: I/O error does not occur when phone is not connected, so very likely power issue with RPi4.

**Pull request closed without merging**
