### PR TITLE
verify-configuration.sh: missing CM4 

### PR DESCRIPTION
**Pull request by Arthur-Philip-Dent**
Would be nice to have support for "Raspberry Pi Compute Module 4". 
Is it enough just adding this line in the "verify-configuration.sh"?
Thanks!

### CODE REVIEW

**Comment by marcone** [comment]
> Is it enough just adding this line in the "verify-configuration.sh"?

That should be enough. I've been hesitant to add the compute modules in there because they depend on a carrier board in order to function, and I don't know how to tell whether the carrier board it is connected to has the required functionality. Which IO board are you using? (the standard IO board from Raspberry Pi seems a bit big to use in the car)

**Comment by Arthur-Philip-Dent** [comment]
> That should be enough. 

Great!  :-) 
I mean really: Thanks for all the fish, @marcone ! 

> I've been hesitant to add the compute modules in there because they depend on a carrier board in order to function, 

Totally with you. This was the razors-edge I had to jump over, tonight, forking the code and trying to make it work - was worth it: it finally works! 

> Which IO board are you using? (the standard IO board from Raspberry Pi seems a bit big to use in the car)

Its a WaveShare CM4-IO-BASE-C, which comes in a bundle as CM4-IO-BASE-BOX-C in a metal case. It has similar features, than the CM4-IO-BASE-B. I picked the BASE-C, since I found some hints, that the BASE-B might have some problems providing enough power to the M.2 connector. 
They come both in a set with metal-cases. The BASE-BOX-C has connectors to one side and antenna to the other side. 
Both are a tad smaller, than a Rspi 4B case. 
Base issue for me was the missing 5G WiFi (and hence, the missing bandwidth) and no RTC. The M.2 is a "nice gimmick", but no record breaking device not furiously faster, than a USB3 linked SSD.

[WaveShare CM4-IO-BASE-C](https://www.waveshare.com/wiki/CM4-IO-BASE-C)

Find for completeness the diagnostics.txt and the teslausb-headless-setup.log attached: 
[diagnostics.txt](https://github.com/marcone/teslausb/files/12446935/diagnostics.txt)
[teslausb-headless-setup.log](https://github.com/marcone/teslausb/files/12446936/teslausb-headless-setup.log)

This are the parameters in the config.txt (fan does not yet slow down, seems I have to configure some gpio for it...)

```

# Removed Enable audio (loads snd_bcm2835)
#dtparam=audio=on

# Removed Automatically load overlays for detected cameras
#camera_auto_detect=1

# Automatically load overlays for detected DSI displays
#display_auto_detect=1

# Removed DRM VC4 V3D driver
# dtoverlay=vc4-kms-v3d
# max_framebuffers=2

# commented compensation for displays with overscan
#disable_overscan=1

[pi4]
# Run as fast as firmware / board allows
arm_boost=1


[cm4]
# Enable host mode on the 2711 built-in XHCI USB controller.
# This line should be removed if the legacy DWC2 controller is required
# (e.g. for USB device mode) or if USB support is not required.
# otg_mode=1
dtoverlay=dwc2
# remove following line, if appended: this is only for 
# accessing the emmc or the SD-Card via USB-C
# dtoverlay=dwc2,dr_mode=host 
# Switch antenna:
# ant1 internal antenna
# ant2 antenna via external connector
# noant Disable both antennas 
dtparam=ant2

[all]

# FAN-Control via config.txt: 
dtoverlay=cm4io-fan,minrpm=500,maxrpm=5000,midtemp=45000,midtemp_hyst=2000,maxtemp=50000,maxtemp_hyst=2000
# FAN-Control via i2c
dtparam=i2c_arm=on
dtparam=i2c_vc=on
RTC via i2c
dtoverlay=i2c-rtc,pcf85063a,i2c_csi_dsi

```

**Comment by Arthur-Philip-Dent** [comment]
If there is any critics, feel free romping out. I just started learning how to handle GitHub and shell scripting.

**Comment by Arthur-Philip-Dent** [comment]
Oh nooo! It was too late yesterday evening and I didn't check, if the emulated drives were mounted through the UB2.0 device... 
I ran into that problem: which is described here (and still not solved... still learning... )
https://github.com/raspberrypi/firmware/issues/1500

**Comment by Arthur-Philip-Dent** [comment]
Hm, I could need a hint. 
Yesterday the M.2 SSD locked up and can be booted from, but throws errors and is somehow locked up... the partition and/or disk seems to be "immutable"... this happend somehow when I was interrupting the "create-backingfiles.sh", since it took very long, and rebooted, finding the SSD locked up. 

 help wanted.... 
 
 Edit: By the chances, that the SSD AND the SD-Card got bonkers the same time, I think, it has nothing to do with the software or the process. My conclusion: It was simply my stupidity rebooting the device or some unlucky incident having somewhere else trouble, like in the power supply. 

I will continue somewhen later this year to get the CM4 working in some kind with some board to make an alternative to enrich the possible SBCs. 

@marcone: if it's ok, I close this pull request, since I was not able to bring up a working device circumventint all the obstacles with the board...

**Comment by Arthur-Philip-Dent** [comment]
I got the cm4 module working on the @waveshare CM4-IO-Board-Box-C, EXECPT of USB2.0 gedget mode. 
Finally the IO-Board-manufacturer replied with the info, that this board can't switch any USB sockets to gadget mode. 

EDIT: The manufacturer recommended the CM4-IO-NANO-A board, which can use USB-C for power and gadget-device connection. 
I have a similar board, the CM4-to-Pi4-Adapter, with which I was able to install the TeslaUSB on a bullseye 64bit Raspian and gadget-mode was working. 

Just had a smal lissue with the sudo -i is asking for pw of pi-user (user id 1000 not in sudoer group nor in /etc/sudoers ). 
Fixing this needs just: 
echo '<user_name> ALL=(ALL:ALL) NOPASSWD:ALL' > /etc/sudoers.d/1000_<user_name>

CM4-IO-NANO-A: https://www.waveshare.com/cm4-nano-a.htm
CM4-to-Pi4-Adapter: https://www.waveshare.com/wiki/CM4-to-Pi4-Adapter

Cheers!

**Comment by Arthur-Philip-Dent** [comment]
Closed, until there is a real chance to get a cm4 to work somehow.

**Comment by Arthur-Philip-Dent** [comment]
Update: I got it working now with gadget mode for the CM4-to-Pi4-adapter and the CM4-IO-BASE-BOX-C. 
dmesg: 
TeslaPi@teslacam:~ $ dmesg | grep -E 'Compute|dwc2|rtc|nvme'
[    0.000000] Machine model: Raspberry Pi Compute Module 4 Rev 1.1
[    0.000000] Kernel command line: coherent_pool=1M 8250.nr_uarts=0 snd_bcm2835.enable_headphones=0 bcm2708_fb.fbwidth=0 bcm2708_fb.fbheight=0 bcm2708_fb.fbswap=1 smsc95xx.macaddr=E4:5F:01:E5:57:3F vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  console=ttyS0,115200 console=tty1 root=PARTUUID=02e846fe-02 rootfstype=ext4 fsck.repair=yes rootwait modules-load=dwc2,g_ether fsck.mode=auto noswap ro
[    0.000000] Unknown kernel command line parameters "noswap modules-load=dwc2,g_ether", will be passed to user space.
[    1.407715] nvme nvme0: pci function 0000:01:00.0
[    1.407870] nvme 0000:01:00.0: enabling device (0000 -> 0002)
[    1.411019] nvme nvme0: missing or invalid SUBNQN field.
[    1.413874] nvme nvme0: allocated 16 MiB host memory buffer.
[    1.420226] nvme nvme0: 4/0/0 default/read/poll queues
[    1.424218] nvme nvme0: Ignoring bogus Namespace Identifiers
[    1.426480]  nvme0n1: p1 p2 p3 p4
[    1.591162] EXT4-fs (nvme0n1p2): mounted filesystem with ordered data mode. Quota mode: none.
[    1.621269]     modules-load=dwc2,g_ether
[    2.873941] dwc2 fe980000.usb: supply vusb_d not found, using dummy regulator
[    2.874306] dwc2 fe980000.usb: supply vusb_a not found, using dummy regulator
[    3.093241] dwc2 fe980000.usb: EPs: 8, dedicated fifos, 4080 entries in SPRAM
[    3.093721] dwc2 fe980000.usb: DWC OTG Controller
[    3.093777] dwc2 fe980000.usb: new USB bus registered, assigned bus number 1
[    3.093851] dwc2 fe980000.usb: irq 41, io mem 0xfe980000
[    3.094431] usb usb1: Manufacturer: Linux 6.1.21-v8+ dwc2_hsotg
[    3.157149] dwc2 fe980000.usb: bound driver g_ether
[    3.326587] dwc2 fe980000.usb: new device is high-speed
[    3.365164] dwc2 fe980000.usb: new address 14
[    4.012200] EXT4-fs (nvme0n1p2): re-mounted. Quota mode: none.
[    5.576840] EXT4-fs (nvme0n1p4): mounted filesystem with ordered data mode. Quota mode: none.
[    5.991777] rtc-pcf85063 10-0051: registered as rtc0
[    5.994341] rtc-pcf85063 10-0051: setting system clock to 2023-09-11T17:25:19 UTC (1694453119)
[    6.121622] XFS (nvme0n1p3): Mounting V5 Filesystem
[    6.165807] XFS (nvme0n1p3): Starting recovery (logdev: internal)
[    6.172743] XFS (nvme0n1p3): Ending recovery (logdev: internal)
[   55.145238] dwc2 fe980000.usb: bound driver configfs-gadget.teslausb
[   55.311752] dwc2 fe980000.usb: new device is high-speed
[   55.354486] dwc2 fe980000.usb: new address 14

TeslaPi@teslacam:~ $ uname -a
Linux teslacam 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
TeslaPi@teslacam:~ $ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
T

**Comment by Arthur-Philip-Dent** [comment]
Update: I got it working now with gadget mode for the CM4-to-Pi4-adapter and the CM4-IO-BASE-BOX-C.
Both require a Y-cable since data and power is fed through the USB-C plug. measured around 700mA, but had no proper setup for measuring peaks during boot, so it could be easily more. 
Switchten off hdmi, network and bt and booting with no "underpower" was possible, but this is not reliable. 

Tesla Model3 pre facelift delivers not enough power through one cable. Will try to find a Y-Cable on 2x USB-A to USB-C

This week a CM4-NANO-BOARD-A arrives. It has no NVMe, no LAN, but RTC. Spoke with the manufacturer, this will work through the USB-C port for power and data, has much less consumption. Is my favourite solution for now, besides the "blow it all CM4-IO-BASE-BOX-C" solution. 

dmesg of CM4-IO-BASE-BOX-C:
TeslaPi@teslacam:~ $ dmesg | grep -E 'Compute|dwc2|rtc|nvme'
[ 0.000000] Machine model: Raspberry Pi Compute Module 4 Rev 1.1
[ 0.000000] Kernel command line: coherent_pool=1M 8250.nr_uarts=0 snd_bcm2835.enable_headphones=0 bcm2708_fb.fbwidth=0 bcm2708_fb.fbheight=0 bcm2708_fb.fbswap=1 smsc95xx.macaddr=E4:5F:01:E5:57:3F vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000 console=ttyS0,115200 console=tty1 root=PARTUUID=02e846fe-02 rootfstype=ext4 fsck.repair=yes rootwait modules-load=dwc2,g_ether fsck.mode=auto noswap ro
[ 0.000000] Unknown kernel command line parameters "noswap modules-load=dwc2,g_ether", will be passed to user space.
[ 1.407715] nvme nvme0: pci function 0000:01:00.0
[ 1.407870] nvme 0000:01:00.0: enabling device (0000 -> 0002)
[ 1.411019] nvme nvme0: missing or invalid SUBNQN field.
[ 1.413874] nvme nvme0: allocated 16 MiB host memory buffer.
[ 1.420226] nvme nvme0: 4/0/0 default/read/poll queues
[ 1.424218] nvme nvme0: Ignoring bogus Namespace Identifiers
[ 1.426480] nvme0n1: p1 p2 p3 p4
[ 1.591162] EXT4-fs (nvme0n1p2): mounted filesystem with ordered data mode. Quota mode: none.
[ 1.621269] modules-load=dwc2,g_ether
[ 2.873941] dwc2 fe980000.usb: supply vusb_d not found, using dummy regulator
[ 2.874306] dwc2 fe980000.usb: supply vusb_a not found, using dummy regulator
[ 3.093241] dwc2 fe980000.usb: EPs: 8, dedicated fifos, 4080 entries in SPRAM
[ 3.093721] dwc2 fe980000.usb: DWC OTG Controller
[ 3.093777] dwc2 fe980000.usb: new USB bus registered, assigned bus number 1
[ 3.093851] dwc2 fe980000.usb: irq 41, io mem 0xfe980000
[ 3.094431] usb usb1: Manufacturer: Linux 6.1.21-v8+ dwc2_hsotg
[ 3.157149] dwc2 fe980000.usb: bound driver g_ether
[ 3.326587] dwc2 fe980000.usb: new device is high-speed
[ 3.365164] dwc2 fe980000.usb: new address 14
[ 4.012200] EXT4-fs (nvme0n1p2): re-mounted. Quota mode: none.
[ 5.576840] EXT4-fs (nvme0n1p4): mounted filesystem with ordered data mode. Quota mode: none.
[ 5.991777] rtc-pcf85063 10-0051: registered as rtc0
[ 5.994341] rtc-pcf85063 10-0051: setting system clock to 2023-09-11T17:25:19 UTC (1694453119)
[ 6.121622] XFS (nvme0n1p3): Mounting V5 Filesystem
[ 6.165807] XFS (nvme0n1p3): Starting recovery (logdev: internal)
[ 6.172743] XFS (nvme0n1p3): Ending recovery (logdev: internal)
[ 55.145238] dwc2 fe980000.usb: bound driver configfs-gadget.teslausb
[ 55.311752] dwc2 fe980000.usb: new device is high-speed
[ 55.354486] dwc2 fe980000.usb: new address 14

TeslaPi@teslacam:~ $ uname -a
Linux teslacam 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr 3 17:24:16 BST 2023 aarch64 GNU/Linux
TeslaPi@teslacam:~ $ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

20230911_173408259_iOS

**Pull request closed without merging**
