### PR TITLE
Added check for installed overlayroot

### PR DESCRIPTION
**Pull request by herrfrei**
On DietPi the /etc/fstab file is automatically generated by a script, so the read-only mounting code of teslausb does not work correctly. As an alternative, I installed overlayroot and that works fine. This PR adds support for overlayroot to teslausb.

Setup overlayroot:

```shell
apt install overlayroot busybox-static 
echo 'overlayroot=tmpfs' >> /etc/overlayroot.local.conf
reboot
```

### CODE REVIEW

**Comment by marcone** [comment]
> On DietPi the /etc/fstab file is automatically generated by a script, so the read-only mounting code of teslausb does not work correctly

In what way does it not work correctly? I installed TeslaUSB on DietPi, and all of the TeslaUSB entries were added to /etc/fstab, the root partition is mounted read-only during normal operation, and can be remounted read/write using the remountfs_rw script.

**Comment by herrfrei** [comment]
May be that the data partition makes problems. I'll check that again. In
general, wouldn't it be easier to switch to overlayroot?

marcone ***@***.***> schrieb am Sa., 21. Dez. 2024, 18:58:

**Comment by marcone** [comment]
> May be that the data partition makes problems. I'll check that again. In general, wouldn't it be easier to switch to overlayroot?

I prefer to be explicit about which parts of the filesystem are writeable and which parts are temporary, instead of just putting 
a writeable overlay on top of everything.

**Comment by herrfrei** [comment]
Okay. Understood.

marcone ***@***.***> schrieb am Sa., 21. Dez. 2024, 19:38:

**Comment by herrfrei** [comment]
Today I tested a clean installation again and it worked. I don't know what the problem was. Closing this PR.

**Pull request closed without merging**
